version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-management-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./logs:/logs
    networks:
      - library-network

  db:
    image: postgres:16-alpine
    container_name: library-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

volumes:
  postgres-data:
    driver: local

networks:
  library-network:
    driver: bridge